# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{active_directory}
  s.version = "1.5.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam T Kerr - Marlon Moyer"]
  s.date = %q{2011-05-27}
  s.description = %q{ActiveDirectory uses Net::LDAP to provide a means of accessing and modifying an Active Directory data store.  This is a fork of the activedirectory gem.}
  s.email = %q{ajrkerr@gmail.com;marlon@mcmoyer.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "VERSION",
    "active_directory.gemspec",
    "lib/active_directory.rb",
    "lib/active_directory/base.rb",
    "lib/active_directory/computer.rb",
    "lib/active_directory/container.rb",
    "lib/active_directory/field_type/binary.rb",
    "lib/active_directory/field_type/date.rb",
    "lib/active_directory/field_type/dn_array.rb",
    "lib/active_directory/field_type/group_dn_array.rb",
    "lib/active_directory/field_type/member_dn_array.rb",
    "lib/active_directory/field_type/password.rb",
    "lib/active_directory/field_type/timestamp.rb",
    "lib/active_directory/field_type/user_dn_array.rb",
    "lib/active_directory/group.rb",
    "lib/active_directory/member.rb",
    "lib/active_directory/user.rb",
    "test/config.example.yml",
    "test/config.yml",
    "test/group_assignment_test.rb",
    "test/groups_test.rb",
    "test/helper.rb",
    "test/users_test.rb"
  ]
  s.homepage = %q{http://github.com/mcmoyer/activedirectory}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.0}
  s.summary = %q{An interface library for accessing Microsoft's Active Directory.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<net-ldap>, [">= 0.4.0"])
    else
      s.add_dependency(%q<net-ldap>, [">= 0.4.0"])
    end
  else
    s.add_dependency(%q<net-ldap>, [">= 0.4.0"])
  end
end

